/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseTest: typeof import('./../src/components/Base/Test/index.vue')['default']
    BaseTest2: typeof import('./../src/components/Base/Test2/index.vue')['default']
    Popup: typeof import('./../src/components/Popup/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
