/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaseTest: typeof import('./../src/components/Base/Test/index.vue')['default']
    BaseTest2: typeof import('./../src/components/Base/Test2/index.vue')['default']
    Popup: typeof import('./../src/components/Popup/index.vue')['default']
  }
}
